### ISSUE TITLE
Added spanish translation.

### ISSUE THREAD

**Issue by thesikboy** [mmatyas/pegasus-frontend-translations#1]
Add spanish translation. Zipped file.

[Spanish translation.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/1910753/Spanish.translation.zip)

**Comment by thesikboy** [comment]
TS File added as request
[pegasus_sp.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/1911549/pegasus_sp.zip)

**Comment by mmatyas** [comment]
Added, thanks again!
Also I've renamed the file to `es` as apparently that's the ISO code for Spanish.
