### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by ghost** [mmatyas/pegasus-frontend-translations#17]
[pegasus_ar.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/5881795/pegasus_ar.zip)

**Comment by mmatyas** [comment]
Great, thanks! Here's how it looks:

![ar01](https://user-images.githubusercontent.com/4354863/106026832-94bce600-60ca-11eb-950b-17a0441f55ec.png)

Now I understand this is a right-to-left locale; is the current layout still readable in your opinion?

**Comment by ghost** [comment]
Yes It looks good. I tested it beforehand (wish I didn't have to compile). Thanks for your work :)

**Comment by mmatyas** [comment]
Added to the latest version, thanks again!
