### ISSUE TITLE
Russian updated translation

### ISSUE THREAD

**Issue by mrqside** [mmatyas/pegasus-frontend-translations#18]
I have also modified FilterPanel section for a new code

[pegasus_ru.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/7025989/pegasus_ru.zip)

**Comment by mmatyas** [comment]
Thanks! Tried it out, looks good, but I noticed one of the labels is quite long on the Gamepad screen:

![image](https://user-images.githubusercontent.com/4354863/130455477-4f9058ff-a9df-4dbf-bd16-8e48d6bdcfb9.png)

Is there a shorter expression you can use there? Leaving it as ABXY is fine too.

**Comment by mrqside** [comment]
Updated
[pegasus_ru.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/7033043/pegasus_ru.zip)

**Comment by mmatyas** [comment]
Ok, this should be available now in the latest release, thanks!
