### ISSUE TITLE
Lithuanian translation

### ISSUE THREAD

**Issue by mrqside** [mmatyas/pegasus-frontend-translations#19]
[pegasus_lt.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/7026115/pegasus_lt.zip)

**Comment by mmatyas** [comment]
Thanks! Will try it out tomorrow.

**Comment by mrqside** [comment]
Spotted small thing, not actually a mistake, but better to update
line 267
from:
<translation>Slinkite puslapiu žemyn</translation>
to
<translation>Slinkti puslapiu žemyn</translation>

Updated file:
[pegasus_lt.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/7033057/pegasus_lt.zip)

**Comment by mmatyas** [comment]
Ok, this should be available now in the latest release, thanks!
