### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by johnnydement** [mmatyas/pegasus-frontend-translations#24]
Hi,

I'm not quite versed in github... so I just translated Pegasus into Catalan language and dropping it here ;)

[pegasus_ca.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/11425644/pegasus_ca.zip)

I used Crowdin, but uploaded it also to Transifex, as it has github integration and is free for non profit software… you might want to create your own project there, use this as a demo if you like: https://app.transifex.com/johnnydement/pegasus-3/dashboard/

**Comment by mmatyas** [comment]
Thanks! I've tried it out, and the translation works fine. Two small issues I've found:

- On the gamepad screen the axis names seem to have different capitalization (eg. eix/Eix):

![image](https://user-images.githubusercontent.com/4354863/237059559-f2e675db-5f7b-44cc-96e2-735c9596eab3.png)

- The `(timeout in %1 seconds)` entries have an intentional line break; if your editor supports this, please keep the line break, but in case it doesn't, I can add it manually too.

**Comment by johnnydement** [comment]
Fixed it yesterday but couldn't upload on the phone, sorry ^^'

Here is the fixed version, I modified the Axis text to prioritize axis vs Stick, thanks for noticing!

If you're examining options online, I suggest giving a look to Transifex. You can check there the project I created, as it opens for github integration, centralization and always up-to-date files for translators, as well as translation memory and other language suggestions, it's free for open-source projects.

Furthermore, is easy to say someone, if you want to translate, go there and start ;)

[pegasus_ca.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/11441223/pegasus_ca.zip)

**Comment by mmatyas** [comment]
Ok, looks fine now!

Yes, I was thinking about setting up a web-based translation page before, and Transifex indeed looks like a nice option. Thanks for the recommendation!

**Comment by johnnydement** [comment]
You're welcome, it's been the unnoficial Joomla! community service for quite some years already, and the official one for the project itself more recently.

Let me know if the spanish one is need of an update as well.

**Comment by mmatyas** [comment]
Well this went better than expected. When I tried it a few years ago I had some troubles, but everything seems to work fine now. I've set up a project at https://app.transifex.com/pegasus/pegasus-frontend/; there's plenty of Spanish text left, if you're interested :wink:

**Comment by mmatyas** [comment]
I think the original issue is resolved now.
