### ISSUE TITLE
Translation updates, 2019-11

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/pegasus-frontend-translations#9]
Updated the language files to the latest version of Pegasus (see [English base file changes](https://github.com/mmatyas/pegasus-frontend-translations/commit/7a2d2ae004257e440e599512cb74dce911641e99)). The following translation have been updated so far:

- [x] de
- [ ] es
- [x] fr
- [x] hu
- [ ] ko
- [x] pt-BR
- [x] ru

Feel free to open pull requests or attach the translated files here. In case you no longer wish to work on this or get notified, just let me know.

CC @cosmo0 @Genetik57 @losernator @Purq @rutantan @thesikboy

**Comment by MephistoSatanDevil** [comment]
[pegasus_zh.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/4099268/pegasus_zh.zip)

Chinese translated files
zh_CN

**Comment by waitingmoon** [comment]
I made a Japanese translation.
[pegasus_ja.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/7160140/pegasus_ja.zip)

**Comment by mmatyas** [comment]
Thank you! Added in 4a5a57b. I've found a small typo (line 33, metadat**e**), but I've fixed that.

I've also noticed the _Suspend_ text was not available for translation, I will update the files in a second.

**Comment by mmatyas** [comment]
Ok, updated the files, @waitingmoon could you tell me a translation for this line: https://github.com/mmatyas/pegasus-frontend-translations/blob/b3a72e1c1f03eba63d43aeb35dc6bd8f9194d307/pegasus_ja.ts#L294 ? I'll quickly add it to the file then.

**Comment by waitingmoon** [comment]
Thanks for fixing my mistake. the translation for that line is スリープ.

**Comment by mmatyas** [comment]
Ok, updated, thanks!

**Comment by johnnydement** [comment]
Hi,

I'm not quite versed in github... so I just translated Pegasus into Catalan language (ca-ES) and dropping it here ;)

[pegasus_ca.zip](https://github.com/mmatyas/pegasus-frontend-translations/files/11425644/pegasus_ca.zip)

I used Crowdin, but uploaded it also to Transifex, as it has github integration and is free for non-profit software… you might want to create your own project there, use this as a demo if you like: https://app.transifex.com/johnnydement/pegasus-3/dashboard/

I could also do the es-ES  one if no one maintains it.

**Comment by mmatyas** [comment]
I think this can be closed, those who wish to update the translation can always send an update of course.

**Comment by johnnydement** [comment]
Yes, ofc, I'm triing to apply for the cat and spanish languages in transifex to mantain them, but I can't, when I pick them I'm sent to another project I work for...

**Comment by mmatyas** [comment]
Hm interesting, is this a Transifex bug?

**Comment by johnnydement** [comment]
Seems so, whenever I go to https://explore.transifex.com/pegasus/pegasus-frontend/ I'm logged out, and when I log in, I'm taken elsewhere -_-

It doesn't matter what browser I use

**Comment by johnnydement** [comment]
Seems It worked this time 🥳

**Comment by mmatyas** [comment]
Turns out there were some messages hidden under one of the submenus, about which I didn't receive any notifications, neither on the page or in mail... oh well, it should work now, I think.

**Comment by johnnydement** [comment]
It does, you have Spanish translated too, I replaced some original translations with what, I think, are more correct ones (and some spelling mistakes) making it consistent with the Catalan one.

As I'm no revisor, can't toggle them as revised, though.

**Comment by mmatyas** [comment]
I'm trying to make sense of Transifex... with not much luck due to all the bugs :sweat: I've sent you an invitation to be reviewer, but it apparently removed (?) your translation role.

**Comment by johnnydement** [comment]
Don't worry, It's a pyramid system, not a tag one, reviewers are translators, that can also approve between translators suggestions. No translation is deleted, and they all remain as suggestions, can be changed any moment.

May I ask to do the same for Catalan?

**Comment by mmatyas** [comment]
Oh I see, that makes sense, thanks!
